project:
  type: website
  output-dir: docs
website:
  title: "Hannah's Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/hannahbarrow
format:
  html:
    theme: morph
    css: style.css

editor: visual